algoritmo "semnome"
var
   count : inteiro
inicio
   enquanto count < 10 faca
      escreval(count)
      count <- count + 1
   fimenquanto
   escreval("Fim enquanto")
   count <- 0
   repita
      escreval(count)
      count <- count + 1
   ate count > 10
   escreval("Fim repita")
   para count de 0 ate 3 passo 1 faca
      escreval(count)
   fimpara
   escreval("Fim para")
fimalgoritmo
